<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
<!ELEMENT students (student+)>
<!ELEMENT student (name, age, course)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT course (#PCDATA)>
]>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>

<students>
    <student>
        <name>John</name>
        <age>20</age>
        <course>Computer Science</course>
    </student>
    <student>
        <name>Alice</name>
        <age>22</age>
        <course>Information Technology</course>
    </student>
</students>